[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api/giveaway"
  to = "/.netlify/functions/giveaway-api"
  status = 200

[[redirects]]
  from = "/api/se-proxy"
  to = "/.netlify/functions/se-proxy"
  status = 200

[[redirects]]
  from = "/api/user-api"
  to = "/.netlify/functions/user-api"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"